### ISSUE TITLE
Contributors missing, issues not linked

### ISSUE THREAD

**Issue by greggles** [mglaman/drupal-mrn#13]
Trying to create release notes for security_review from 8.x-1.0-alpha2 to 8.x-1.0 and the output is:

```
                <p><em>Add a summary here</em></p>
<h3>Contributors (0)</h3>
<p></p>
<h3>Changelog</h3>
<p><strong>Issues:</strong> 0 issues resolved.</p>
<p>Changes since <a href="https://www.drupal.org/project/security_review/releases/8.x-1.0-alpha2">8.x-1.0-alpha2</a>:</p>
<h4>Misc</h4>
<ul>
  <li>Fix issue 3178420</li>
  <li>Fix issue 3138626</li>
  <li>Fix issue 3314121</li>
  <li>Fix issue 2830729</li>
  <li>Fix issue 3155645</li>
  <li>Fix issue 3008225</li>
  <li>Fix issue 3000135</li>
  <li>Fix issue 3094916</li>
  <li>Fix issue 2404219</li>
</ul>
```

The Contributors of zero seems wrong and the issues do not have the `[#1234]` style that I expect.

**Comment by mglaman** [comment]
@greggles those looks like the descriptions from the GItLab merge requests 🤔

**Comment by mglaman** [comment]
It's working fine. The commits don't match standards. This is closer to #12. Without the leading `#` at the issue ID, it's near impossible to know if that is intended to be a ticket number. Although, I guess we know Drupal.org issue IDs are all integer at a specific length.

![Screen Shot 2022-11-10 at 9 44 10 AM](https://user-images.githubusercontent.com/3698644/201140320-4cc2fb97-f90a-4ad4-9e58-e20705765682.png)

**Comment by mglaman** [comment]
I'm going to close this as it'll be fixed/improved by #12 and #14

**Comment by greggles** [comment]
Got it. Sorry. I didn't even think of that :/

Maybe the drupal-mrn tool should provide a warning if comments are found that are not the proper format?

**Comment by mglaman** [comment]
That makes sense. When parsing, bubble errors to be returned.
