### ISSUE TITLE
Add some meta tags to make this tool look as cool as it is when shared

### ISSUE THREAD

**Issue by thejimbirch** [mglaman/drupal-mrn#183]
PR to follow

**Comment by mglaman** [comment]
I think the `og:image` value has to be absolute https://drupal-mrn.dev/mrn.png

**Comment by thejimbirch** [comment]
![image](https://github.com/mglaman/drupal-mrn/assets/5177009/cbb0cef3-3179-4d12-8d3d-ea84a7f3336a)

You're probably right. I can send a pr when I am back at my computer, but Slack is picking it up now. 

Thanks for the cool tool!

**Comment by mglaman** [comment]
Oh cool that worked? A demo tool said it wasn't valid. Either way, thank you for this!

**Comment by thejimbirch** [comment]
This was closed in #184
