### ISSUE TITLE
Display a dropdown of tags for From/To

### ISSUE THREAD

**Issue by mglaman** [mglaman/drupal-mrn#5]
After #4, once the project is selected, an API call should get the tags for a project (unless that API call can do so as well.) Then the From/To are dropdowns of valid tags.

**Comment by ylynfatt** [comment]
+1 for this 👍🏽. It would definitely be helpful. I made the mistake of not entering the tag properly.

I guess initially the API call can return the last two valid tags and use in the 2nd to last one in the "from" field and the last (most recent) one in the "to" field.

**Comment by mglaman** [comment]
Instead of a dropdown, it should use a datalist so it can be autocompleted https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
